# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deploy Production

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    name: "deploy"
    runs-on: [self-hosted]
    steps:
    - name: Force Pulling
      run: |
        cd /home/hml.martx.com.br/martx-sneakers-api
        git stash
        git pull origin master
    - name: install dependencies
      run: |
        cd /home/hml.martx.com.br/martx-sneakers-api/
        composer install
    - name: migrate database
      run: |
        cd /home/hml.martx.com.br/martx-sneakers-api/
        php artisan migrate:fresh --force